- README.md
> update lens creation in Readme

- core/src/main/scala/monocle/Lens.scala
- core/src/main/scala/monocle/Optional.scala
* Removed unnecessary indirections via 
getOrModify in Optional.
* Removed unnecessary indirections via
set in Lens and Optional.
> Some micro-optim. in Optional/Lens apply.

- core/src/main/scala/monocle/Fold.scala
- core/src/main/scala/monocle/Optional.scala
- core/src/main/scala/monocle/Setter.scala
- core/src/main/scala/monocle/Traversal.scala
- test/src/test/scala/monocle/OptionalSpec.scala
for all o: Optic[S, A], o compose void[A, B] == void[S, B]
> add void for Optional, traversal, Fold and Setter

- core/src/main/scala/monocle/std/Option.scala
- test/src/test/scala/monocle/std/OptionSpec.scala
> Add Iso between Option and Disjunction

- core/src/main/scala/monocle/Fold.scala
- core/src/main/scala/monocle/Traversal.scala
- test/src/test/scala/monocle/FoldSpec.scala
- test/src/test/scala/monocle/TraversalSpec.scala
https://hackage.haskell.org/package/lens-4.12.3/docs/Control-Lens-Fold.html#v:lengthOf
> add length method for Fold

- core/src/main/scala/monocle/std/Either3.scala
- core/src/main/scala/monocle/std/StdInstances.scala
- test/src/test/scala/monocle/TestInstances.scala
- test/src/test/scala/monocle/std/Either3Spec.scala
> Add optics for scalaz.Either3

- .travis.yml
I regenerated sonatype credential, who knows if it will help ...
> attempt to fix auto publish

- core/src/main/scala/monocle/Fold.scala
- core/src/main/scala/monocle/Getter.scala
- core/src/main/scala/monocle/Iso.scala
- core/src/main/scala/monocle/Lens.scala
- core/src/main/scala/monocle/Optional.scala
- core/src/main/scala/monocle/Setter.scala
- core/src/main/scala/monocle/Traversal.scala
The idea is to have consistent method name with typeclass.
> Rename sum to choice and product to split

- .travis.yml
- README.md
- build.sbt
http://www.scala-lang.org/news/2.10.6
> update scala version to 2.10.6

- core/src/main/scala/monocle/std/NonEmptyList.scala
https://github.com/scalaz/scalaz/blob/v7.1.4/core/src/main/scala/scalaz/NonEmptyList.scala#L117
> modify to use NonEmptyList#zipWithIndex

- docs/src/main/tut/prism.md
- docs/src/site/_layouts/default.html
- docs/src/site/learning_resources.md
Please tell me if you have any other resources to add
> fix #251 add learning resources to the website

- README.md
> add maven badge

- build.sbt
- date/src/main/scala/monocle/date/Joda.scala
- date/src/main/scala/monocle/date/package.scala
- test/src/test/scala/monocle/TestInstances.scala
- test/src/test/scala/monocle/generic/JodaSpec.scala
... of refined types like `Minute` and `Hour`
> Use refined-scalacheck for Arbitrary instances

- core/src/main/scala/monocle/Fold.scala
- core/src/main/scala/monocle/Getter.scala
- core/src/main/scala/monocle/Iso.scala
- core/src/main/scala/monocle/Prism.scala
- test/src/test/scala/monocle/IsoSpec.scala
- test/src/test/scala/monocle/LensSpec.scala
- test/src/test/scala/monocle/OptionalSpec.scala
- test/src/test/scala/monocle/PrismSpec.scala
I don't think we can write a lawful `left` or `right` for any `Lens`, `Optional` or above. The main issue comes from the definition of `set`.
> left & right

- .travis.yml
- docs/src/main/tut/iso.md
- docs/src/main/tut/lens.md
- docs/src/main/tut/prism.md
- docs/src/site/optics.md
Fix errors and add some smaller hints
Hopefully this incorporates all the changes now and can be merged.
> Add documentation for Iso

- build.sbt
ref.
https://gitter.im/milessabin/macro-compat?at=563b65c65680530d27049fa2
> update macro-compat version to 1.0.6

- core/src/main/scala/monocle/std/Cofree.scala
- core/src/main/scala/monocle/std/Free.scala
- core/src/main/scala/monocle/std/IList.scala
- core/src/main/scala/monocle/std/List.scala
- core/src/main/scala/monocle/std/Stream.scala
- core/src/main/scala/monocle/std/String.scala
- core/src/main/scala/monocle/std/Tree.scala
- core/src/main/scala/monocle/std/Vector.scala
- example/src/test/scala/monocle/JsonExample.scala
- test/src/test/scala/monocle/std/StringSpec.scala
- test/src/test/scala/monocle/std/VectorSpec.scala
And change the plate definitions to vals.
> Plated for String and Vector

- refine/src/main/scala/monocle/refine/internal/Bits.scala
As noted in https://github.com/julien-truffaut/Monocle/pull/291#issuecomment-157000031
> Correct Bits[Long].bitSize

- macro/src/main/scala/monocle/macros/internal/Macro.scala
> Generate fresh type-parameter name for modifyF

- .travis.yml
- README.md
- build.sbt
- docs/src/site/index.md
ref. https://github.com/julien-truffaut/Monocle/issues/330
> update scala version to 2.11.8

- docs/src/site/_layouts/default.html
- docs/src/site/adopters.md
> add adopters section

- .travis.yml
- build.sbt
> add scalac option for java8

- core/shared/src/main/scala/monocle/function/At.scala
- example/src/test/scala/monocle/function/AtExample.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
> rename sans to remove

- build.sbt
Follow-up to https://github.com/julien-truffaut/Monocle/pull/348
> Update refined-scalacheck to 0.4.0 too

- README.md
> Remove unbalanced opening bracket

- docs/src/site/optics.md
> Fixed typo in optics.md

- README.md
- docs/src/site/index.md
- docs/src/site/release_note.md
1.2.2 is on its way to maven central
> post release update for 1.2.2

- README.md
@nuttycom Could you double check?
> fix #382 add imports to the Readme and update usage of HeadOption

- core/shared/src/main/scala/monocle/function/Plated.scala
- example/src/test/scala/monocle/std/TreeExample.scala
- test/shared/src/test/scala/monocle/function/PlatedSpec.scala
I've recently used this great library for transformation of nested structure. One thing that I founded out that was missed is the ability to count number of changes. I've prepared the function that can make it. Maybe it wil be helpfull for others. WDYT?
> Added to Plated transformation counting number of changes

- build.sbt
ref.
https://github.com/scala-js/scala-js/pull/2395
https://github.com/scala-js/scala-js/issues/2579
> Update build settings

- .travis.yml
- build.sbt
- docs/src/site/release_note.md
- project/build.properties
- project/plugins.sbt
> upgrade dependencies for scala 2.12

- build.sbt
- project/plugins.sbt
https://github.com/typesafehub/migration-manager/blob/0.1.11/sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/Keys.scala#L10-L11
> fix warning

- docs/src/main/resources/microsite/data/menu.yml
- docs/src/main/tut/docs/optics.md
- docs/src/main/tut/docs/optics/optional.md
New PR for Optional documentation, sbt-microsite ready
> Add Optional documentation, sbt-microsite ready

- docs/src/main/tut/docs/learning_resources.md
> add link to Ilan presentation on youtube

- core/shared/src/main/scala/monocle/Iso.scala
> fix #428 correct Iso javadoc

- core/shared/src/main/scala/monocle/syntax/Apply.scala
> Add missing methods for `ApplyFold` and `ApplyPrism`

- core/shared/src/main/scala/monocle/syntax/Apply.scala
Fixes part of #439 
Added methods for Iso, Lens, Optional, Traversal, Getter
> Adding missing methods to Apply optics - Part2

- refined/shared/src/main/scala/monocle/refined/All.scala
- refined/shared/src/main/scala/monocle/refined/chars.scala
- refined/shared/src/main/scala/monocle/refined/package.scala
- test/shared/src/test/scala/monocle/refined/CharSpec.scala
> Add support for refined Char (lowercase and uppercase)

- build.sbt
> remove scalac options to compile scala 2.11 with java8

- docs/src/main/tut/examples/university_example.md
- docs/src/main/tut/optics/iso.md
- docs/src/main/tut/optics/lens.md
- docs/src/main/tut/optics/optional.md
- docs/src/main/tut/optics/prism.md
- docs/src/main/tut/optics/traversal.md
- docs/src/main/tut/unsafe_module.md
I read through the document and found these.
(My fixes can be wrong, so please someone review carefully :)
> Fix document

- core/shared/src/main/scala/monocle/function/Possible.scala
- docs/src/main/resources/microsite/data/menu.yml
- docs/src/main/tut/typeclasses.md
- docs/src/main/tut/typeclasses/possible.md
- law/shared/src/main/scala/monocle/law/discipline/function/PossibleTests.scala
> Change Possible from Prism to Optional and add link in website

- docs/src/main/tut/index.md
- docs/src/main/tut/release_notes.md
- version.sbt
should be merged after https://github.com/julien-truffaut/Monocle/pull/468
> Prepare 1.4.0-M2

- core/shared/src/main/scala/monocle/function/Each.scala
- test/shared/src/test/scala/monocle/std/TrySpec.scala
> Add Try instance for Each

- core/shared/src/main/scala/monocle/function/Each.scala
- test/shared/src/test/scala/monocle/std/DisjunctionSpec.scala
- test/shared/src/test/scala/monocle/std/EitherSpec.scala
- test/shared/src/test/scala/monocle/std/ValidationSpec.scala
> Add Each instance for Either, Disjunction and Validation

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- test/shared/src/test/scala/monocle/FoldSpec.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/SetterSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
> Add Unzip instance for Lens, Fold, Optional, Traversal, Setter

- refined/shared/src/main/scala/monocle/refined/package.scala
- refined/shared/src/main/scala/monocle/refined/strings.scala
- test/shared/src/test/scala/monocle/refined/StringsSpec.scala
Basically it's similar to one from 'startsWith' Prism with fthomas comments applied.
> Add Support for refined endsWith #481

- core/js/src/main/scala/monocle/std/String.scala
- core/jvm/src/main/scala/monocle/std/String.scala
- core/shared/src/main/scala/monocle/std/String.scala
- test/js/src/test/scala/monocle/PlatformSpecificTestInstances.scala
- test/jvm/src/test/scala/monocle/PlatformSpecificTestInstances.scala
- test/jvm/src/test/scala/monocle/std/PlatformSpecificStringsSpec.scala
- test/shared/src/test/scala/monocle/TestInstances.scala
- test/shared/src/test/scala/monocle/std/StringsSpec.scala
Fix #488 , #489
Maybe there are better/simpler ways to generate `Arbitrary`, `Cogen` instances? Any feedback is welcome :)
> Add URI, URL Prisms

- .travis.yml
avoid regression https://github.com/julien-truffaut/Monocle/issues/492
> execute packageSrc in travis-ci

- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/TestInstances.scala
- test/shared/src/test/scala/other/MacroOutSideMonocleSpec.scala
> Add Equal instance for optics in test

- docs/src/main/tut/adopters.md
> Added Goggles to adopters

- build.sbt
ref. https://github.com/typelevel/scala/issues/135
> update CrossVersion.patch and scalaOrganization.value

- bench/src/main/scala/monocle/bench/BenchModel.scala
- bench/src/main/scala/monocle/bench/LensBench.scala
- bench/src/main/scala/monocle/bench/MonocleLensBench.scala
- bench/src/main/scala/monocle/bench/MonocleMacroLensBench.scala
- bench/src/main/scala/monocle/bench/MonocleTraversalBench.scala
- bench/src/main/scala/monocle/bench/ScalazLensBench.scala
- bench/src/main/scala/monocle/bench/ShapelessLensBench.scala
- bench/src/main/scala/monocle/bench/StdTraversalBench.scala
@sellout it is your call if it is worth it or not
> remove scalaz data types in bench to simplify differences with cats branch

- .travis.yml
- build.sbt
- project/plugins.sbt
fix https://github.com/julien-truffaut/Monocle/issues/517
> scalaz 7.2.12, scala-native 0.2.1

- macro/shared/src/main/scala/monocle/macros/Lenses.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
Does what it says, I'd hope.
Fixes #523.
> Allow for annotations on companion objects of @Lenses-annotated case classes.

- .travis.yml
https://github.com/julien-truffaut/Monocle/pull/533#issuecomment-333065488
> use travis_setup.sh of scala-native

- docs/src/main/tut/optics.md
Carefully check it, please. I could make a mistake.
> Reorder optics composition table #535

- .travis.yml
- build.sbt
add "macrosJVM/compile" and "macrosJS/compile" check for Scala-2.13.0 M4
> fix macro-paradise settings

- .travis.yml
- project/plugins.sbt
> update tut. enable all project build for Scala 2.13.0-M4

- docs/src/main/tut/optics/lens.md
I just would like to add a note about a few standard composition cases.
> update Lens documentation about additional ways to compose

- example/src/test/scala/monocle/generic/CoproductExample.scala
- generic/shared/src/main/scala/monocle/generic/All.scala
- generic/shared/src/main/scala/monocle/generic/CoProduct.scala
- generic/shared/src/main/scala/monocle/generic/Generic.scala
- generic/shared/src/main/scala/monocle/generic/internal/CoproductToDisjunction.scala
- generic/shared/src/main/scala/monocle/generic/internal/DisjunctionToCoproduct.scala
- test/shared/src/test/scala/monocle/generic/CoproductSpec.scala
> Added `coProductIso`/`coProductDisjunctionIso` for cats

- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/internal/IsEq.scala
- core/shared/src/main/scala/monocle/syntax/Apply.scala
- example/src/test/scala/monocle/LensExample.scala
- macro/shared/src/main/scala/monocle/macros/syntax/GenApplyLensSyntax.scala
- state/shared/src/main/scala/monocle/state/ReaderGetterSyntax.scala
- state/shared/src/main/scala/monocle/state/StateGetterSyntax.scala
- state/shared/src/main/scala/monocle/state/StateLensSyntax.scala
- state/shared/src/main/scala/monocle/state/StateOptionalSyntax.scala
- state/shared/src/main/scala/monocle/state/StateSetterSyntax.scala
> Fix implicit syntax collisions for cats

- docs/src/main/tut/release_notes.md
I manually went through https://github.com/julien-truffaut/Monocle/compare/v1.5.0...master
> release note for 1.6.0

- core/shared/src/main/scala/monocle/function/Index.scala
- example/src/test/scala/monocle/function/IndexExample.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
- test/shared/src/test/scala/monocle/std/StreamSpec.scala
- test/shared/src/test/scala/monocle/unsafe/UnsafeSelectSpec.scala
It seems that the Stream updated was causing the failure for Index. The solution is not amazing but we will most likely drop Stream in the release after that.
> #648 fix tests commented for 2.13

- .travis.yml
- build.sbt
- project/plugins.sbt
> [WIP] Scala 2.13.0

- kernel/shared/src/main/scala/monocle/Prism.scala
do you think it makes sense to define them in the companion object of Prism?
> add Option and Either Prism in Prism's companion object

- kernel/shared/src/main/scala/monocle/Lens.scala
- kernel/shared/src/main/scala/monocle/Optional.scala
- kernel/shared/src/main/scala/monocle/Prism.scala
- kernel/shared/src/main/scala/monocle/function/Cons.scala
- kernel/shared/src/main/scala/monocle/function/Field.scala
- Use single type parameter and Aux pattern for typeclass definition
- move optics to companion object of Lens/Prism/...
> Proof of concept for new typeclasses

- dotSyntax/src/main/scala/monocle/syntax/AppliedIso.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedLens.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedOptional.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedPrism.scala
- dotSyntax/src/main/scala/monocle/syntax/iso.scala
- dotSyntax/src/main/scala/monocle/syntax/lens.scala
- dotSyntax/src/test/scala/monocle/syntax/IsoSyntaxTest.scala
- kernel/shared/src/main/scala/monocle/Iso.scala
- kernel/shared/src/main/scala/monocle/function/Reverse.scala
> Implement reverse

- core/shared/src/main/scala/monocle/function/At.scala
- test/shared/src/test/scala/monocle/TestInstances.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
* add `At` instance for `ListMap`
* fixes #739
> #739 Missing instance of At for ListMap

- dotSyntax/src/main/scala/monocle/syntax/AppliedOptional.scala
- dotSyntax/src/main/scala/monocle/syntax/optional.scala
- dotSyntax/src/test/scala/monocle/syntax/OptionalSyntaxTest.scala
- kernel/shared/src/main/scala/monocle/Optional.scala
- kernel/shared/src/main/scala/monocle/function/Possible.scala
Take 2 on the implementation of `Possible`
> Possible implementation

- .travis.yml
- build.sbt
- project/plugins.sbt
The goal is to experiment faster with syntax and kernel.
Should we also remove the source code of those modules?
> Remove from build all unused modules and dependencies for v3 

- .scalafmt.conf
- build.sbt
- dotSyntax/src/main/scala/monocle/syntax/AppliedIso.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedLens.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedOptional.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedPrism.scala
- dotSyntax/src/main/scala/monocle/syntax/applied.scala
- dotSyntax/src/main/scala/monocle/syntax/optional.scala
- dotSyntax/src/main/scala/monocle/syntax/prism.scala
- dotSyntax/src/test/scala/monocle/syntax/IsoSyntaxTest.scala
- dotSyntax/src/test/scala/monocle/syntax/LensSyntaxTest.scala
- dotSyntax/src/test/scala/monocle/syntax/OptionalSyntaxTest.scala
- kernel/shared/src/main/scala/monocle/Iso.scala
- kernel/shared/src/main/scala/monocle/Lens.scala
- kernel/shared/src/main/scala/monocle/Optional.scala
- kernel/shared/src/main/scala/monocle/Prism.scala
- kernel/shared/src/main/scala/monocle/function/At.scala
- kernel/shared/src/main/scala/monocle/function/Cons.scala
- kernel/shared/src/main/scala/monocle/function/Index.scala
- kernel/shared/src/main/scala/monocle/function/Possible.scala
- kernel/shared/src/main/scala/monocle/function/Reverse.scala
- project/plugins.sbt
I don't have a strong preference on the rules.
> add scalafmt

- core/shared/src/main/scala/monocle/function/Each.scala
- test/shared/src/test/scala/monocle/function/EachSpec.scala
* add instance for `Each` using custom `Traversal` for `ListMap`
> Missing instance of Each for ListMap

- kernel/shared/src/main/scala/monocle/Fold.scala
- kernel/shared/src/main/scala/monocle/Getter.scala
- kernel/shared/src/main/scala/monocle/Optional.scala
It is probably a stupid idea but I wanted to give it a try.
An `Iterator` is mutable and cannot be reused but it is simple and it offers both efficient iteration and laziness.
> POC of Fold based on Iterator

- build.sbt
> Scalatest upgrade

- project/build.properties
> Sbt upgrade

- dotSyntax/src/test/scala/monocle/syntax/GetterSyntaxTest.scala
These maybe unneeded given the Lens test but I though it would be nice to have them
> Add test for getter syntax

- macro/src/main/scala/monocle/macros/internal/Macro.scala
> fully import PLens and cats

- build.sbt
Simple lib update, I wonder why scala-steward didn't pick it up
> Upgrade cats

- .travis.yml
- build.sbt
- project/plugins.sbt
This should publish fine for both 0.6 and 1.0
> Support scala.js 1.0

- build.sbt
The skip publication should only apply to the the jvm side
> Skip publication of jvm side only

- build.sbt
I think the reason publication isn't working properly is because the aggregates are published too
> Aggregates

- bench/src/main/scala/monocle/bench/MonocleTraversalBench.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/function/Each.scala
- core/shared/src/main/scala/monocle/function/Plated.scala
- core/shared/src/main/scala/monocle/law/IsoLaws.scala
- core/shared/src/main/scala/monocle/law/LensLaws.scala
- core/shared/src/main/scala/monocle/law/OptionalLaws.scala
- core/shared/src/main/scala/monocle/law/PrismLaws.scala
- example/src/test/scala/monocle/JsonExample.scala
- state/src/main/scala/monocle/state/StateTraversalSyntax.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- unsafe/src/main/scala/monocle/unsafe/MapTraversal.scala
https://github.com/typelevel/kind-projector
>?, +?, and -? (deprecated syntax; same meaning as the above)
> Replace deprecated ? with *

- docs/src/main/mdoc/optics/lens.md
- macro/src/main/scala/monocle/macros/Lenses.scala
https://github.com/optics-dev/Monocle/issues/900
I hope You like it.
I've checked this hyperlink to "Getting started" section by inspecting "production" page and editing other link. I couldn't generate the sites locally, but I'm sure that my link will work as well.
> add extra notes in @Lenses documentation and Lens page

- build.sbt
- state/src/main/scala/monocle/state/StateTraversalSyntax.scala
Build a few more modules with dotty
> Compile unsafe, state, law modules to dotty

- core/shared/src/main/scala/monocle/function/Reverse.scala
Completing the "bonus point" of #868 using #869 implementation.
Beware, it's a heavy PR
> Creating Iso using the new method "involuted" when it is possible

- .github/workflows/release.yml
- .github/workflows/scala.yml
- build.sbt
- project/plugins.sbt
Updates dotty and tries a fix to the doc issue on release
> Scala 3.0.0

- build.sbt
It has been kind of recommended to build for the last two versions of dotty. This PR adds M2 though we still need to solve some issues to get to publish for dotty
> cross build two dotty versions

- core/shared/src/main/scala/monocle/function/All.scala
- core/shared/src/main/scala/monocle/function/At.scala
- law/src/main/scala/monocle/law/discipline/function/AtTests.scala
@julien-truffaut that seems to work
The only question - are the other two type parameters of `At` sufficient to avoid problems with implicits and contravariance.
> Make At contravariant in I so that it works with singletons

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/function/Plated.scala
- core/shared/src/main/scala/monocle/syntax/Apply.scala
- core/shared/src/main/scala/monocle/syntax/ApplyFold.scala
- core/shared/src/main/scala/monocle/syntax/ApplyGetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyIso.scala
- core/shared/src/main/scala/monocle/syntax/ApplyLens.scala
- core/shared/src/main/scala/monocle/syntax/ApplyOptional.scala
- core/shared/src/main/scala/monocle/syntax/ApplyPrism.scala
- core/shared/src/main/scala/monocle/syntax/ApplySetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyTraversal.scala
There was never any proof that those `inline` annotations help in any way.
> Remove @inline

- build.sbt
- refined/src/main/scala/monocle/refined/internal/Bits.scala
- refined/src/main/scala/monocle/refined/package.scala
Lets refined to be compiled with dotty and I removed the restriction to publish on dotty as we don't have dependencies requiring `withDottyCompat`
> refined to compile to dotty and publish dotty packages

- build.sbt
- macro/src/main/scala/monocle/macros/GenIso.scala
- macro/src/main/scala/monocle/macros/GenPrism.scala
- macro/src/main/scala/monocle/macros/internal/Macro.scala
- macro/src/test/scala/monocle/macros/MacroTests.scala
> Macro Perf Test using Probably

- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/syntax/ApplyOptional.scala
- core/shared/src/main/scala/monocle/syntax/ApplyPrism.scala
- docs/src/main/mdoc/optics/optional.md
- docs/src/main/mdoc/optics/prism.md
- example/src/test/scala/monocle/function/HeadOptionExample.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
Closes #1004
Changed the deprecated version number to 3.0.0-M1 in line with the other deprecation changes
> Replace deprecated setOption with replaceOption

- website/i18n/en.json
- website/pages/en/index.js
- website/siteConfig.js
Fix https://github.com/optics-dev/Monocle/issues/1057
> Simpler landing page with Focus

- .scala-steward.conf
https://github.com/scala-steward-org/scala-steward/blob/011d5f32dca9d7c3c28b02c11bbc63e7934e46e9/docs/repo-specific-configuration.md
> add "updates.includeScala = true" setting

- build.sbt
https://github.com/sbt/sbt/pull/6328
> use slash syntax instead of old "in" syntax

- core/shared/src/main/scala-3.x/monocle/internal/focus/features/fieldselect/FieldSelectParser.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusFieldSelectTest.scala
Resolves #1092. Also added some test cases.
> Focus now supports tuple field selection

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/function/At.scala
- core/shared/src/main/scala/monocle/function/Cons.scala
- core/shared/src/main/scala/monocle/function/Cons1.scala
- core/shared/src/main/scala/monocle/function/Index.scala
- core/shared/src/main/scala/monocle/function/Snoc.scala
- core/shared/src/main/scala/monocle/function/Snoc1.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusAtTest.scala
- example/src/test/scala/monocle/function/FieldsExample.scala
- test/shared/src/test/scala/monocle/FoldSpec.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/SetterSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
Recommend to use `Focus` to zoom into tuples.
> Remove At instance for tuples

- docs/src/main/mdoc/examples/university_example.md
They were some errors in this MD, non required import and use of `GenLens`.
Maybe better to ditch this file completely.
> Slightly improve university example

- build.sbt
- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/LambdaConfigParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/ParserBase.scala
- macro/src/main/scala-3.x/monocle/macros/GenPrism.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
RC1 seems to break the Focus parser:
```
[error] -- [E107] Syntax Error: /Users/julien/project/Monocle/core/shared/src/main/scala-3.x/monocle/internal/focus/LambdaConfigParser.scala:23:28
[error] 23 |      case Block(List(DefDef(_, _, _, _, Some(magicFreeLambda))), _) => Some(magicFreeLambda)
[error]    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Wrong number of argument patterns for DefDef; expected: (String, List[LambdaConfigParser.this.macroContext.reflect.ParamClause], LambdaConfigParser.this.macroContext.reflect.TypeTree, Option[LambdaConfigParser.this.macroContext.reflect.Term])
[error] -- [E107] Syntax Error: /Users/julien/project/Monocle/core/shared/src/main/scala-3.x/monocle/internal/focus/LambdaConfigParser.scala:23:28
[error] 23 |      case …
```
> Bump Scala 3 to RC1

- build.sbt
https://github.com/lampepfl/dotty/commit/c9533da391b8511c8aaca17b498a03b18ec6b3a8
> enable scalajs-mapSourceURI option if Scala 3

- build.sbt
I propose to cut a new milestone when we merge this PR.
> Bump Scala 3 to RC3

- core/shared/src/main/scala-3.x/monocle/internal/focus/features/as/AsGenerator.scala
* Avoid access to private module in quotes (see https://github.com/lampepfl/dotty/issues/13215)
* Make code more preformant
> Avoid indirect call to AsPrismImpl

- .github/workflows/scala.yml
- https://github.com/olafurpg/setup-scala/issues/49
> use setup-java instead of setup-scala

- core/shared/src/main/scala/monocle/function/Plated.scala
- test/shared/src/test/scala/monocle/function/PlatedSpec.scala
> fix: re-implements Plated.transformOf

- generic/src/main/scala-2/monocle/generic/HList.scala
- generic/src/main/scala-2/monocle/generic/Product.scala
> add explicit type for implicit methods

- example/src/test/scala-2/other/ImportExample.scala
> add explicit type for implicit

- build.sbt
- https://github.com/sbt/sbt/issues/7408
- https://github.com/scalameta/mdoc/blob/d7b59fbd331786dfda17427a43a37520ebfedfdb/mdoc-sbt/src/main/scala/mdoc/MdocPlugin.scala#L85-L93
> set `run / fork := true`

- .scalafmt.conf
- example/src/test/scala-2/monocle/ComposeIssueExample.scala
- macro/src/main/scala-2/monocle/macros/GenIso.scala
force rewrite to new sytnax. avoid warnings in Scala 3.4
> update scalafmt setting

- macro/src/main/scala-3/monocle/macros/GenIso.scala
https://github.com/scala/scala3/blob/5101daf9f454c23898ec205894a1c97025f39515/library/src/scala/quoted/Quotes.scala#L4816-L4825
> fix warning. `throwError` => `errorAndAbort`
