- macro/src/main/scala/monocle/macros/internal/Macro.scala
- project/plugins.sbt
- test/src/test/scala/monocle/LensSpec.scala
> Enhance GenLens to support select chains i.e. _.a.b.c

- core/src/main/scala/monocle/std/StdInstances.scala
- core/src/main/scala/monocle/std/Validation.scala
- example/src/test/scala/monocle/std/ValidationExample.scala
- test/src/test/scala/monocle/TestUtil.scala
- test/src/test/scala/monocle/std/ValidationSpec.scala
This PR contains optics for scalaz.Validation, (hopefully) completing the work begun in https://github.com/julien-truffaut/Monocle/pull/178:
- the ValidationFunctions provides success and failure implementations, along with a Disjunction Iso implementation
- get, set and modify examples provided in the examples project
- scalacheck properties exercising Prism and Iso Laws defined in the test project.
Happy to add any other optics that might be useful/relevant here.
> add optics for scalaz.Validation

- macro/src/main/scala-2.10/monocle.macros.internal/MacrosCompatibility.scala
- macro/src/main/scala-2.11/monocle.macros.internal/MacrosCompatibility.scala
- macro/src/main/scala/monocle/macros/GenIso.scala
- test/src/test/scala/monocle/IsoSpec.scala
- test/src/test/scala/other/MacroOutSideMonocleSpec.scala
Many thanks to @retronym for helping me out with a Scala 2.10/2.11 issue regarding prefixes, see https://gist.github.com/retronym/4752d7c1dba6fb837ae5 (reproduced below)
```scala
% tail sandbox/{macro,client}.scala
==> sandbox/macro.scala <==
object Macro {
def m[S]: () => S = macro impl[S]
def impl[S : c.WeakTypeTag](c: Context): c.Expr[() => S] = {
import c.universe._
val sym = weakTypeOf[S].typeSymbol.asClass.module
reify(() => c.Expr[S](Ident(sym)).splice)
}
}
==> sandbox/client.scala <==
class Client {
object O
Macro.m[O.type]
}
% (export V=v2.11.6; scalac-hash $V sandbox/macro.scala && scalac-hash $V sandbox/client.scala)
warning: there was one deprecation warning; re-run with -deprecation for details
one warning found
% (export V=v2.10.4; scalac-hash $V sandbox/macro.scala && …
```
> GenIso for objects

- core/src/main/scala/monocle/Iso.scala
- core/src/main/scala/monocle/Lens.scala
- core/src/main/scala/monocle/Optional.scala
- core/src/main/scala/monocle/Prism.scala
- core/src/main/scala/monocle/law/OptionalLaws.scala
- core/src/main/scala/monocle/law/PrismLaws.scala
- macro/src/main/scala/monocle/macros/GenPrism.scala
I never liked the name `getOrModify` but I couldn't find the equivalent in haskell lens.
I completely missed it: https://hackage.haskell.org/package/lens-4.12.3/docs/src/Control-Lens-Prism.html#matching
> renamed getOrModify to matching

- bench/src/main/scala/monocle/bench/MonocleTraversalBench.scala
- build.sbt
- core/src/main/scala/monocle/Traversal.scala
- core/src/main/scala/monocle/std/IMap.scala
- core/src/main/scala/monocle/std/Map.scala
This is a contentious PR.
Intellij 14 / 15 CE does not seem to understand kind projector any more. I believe it started since we migrated from `Build.scala` to `build.sbt` but I cannot tell for sure. Since it is blocking or at least annoying potential contributor (see https://groups.google.com/forum/#!topic/scala-monocle/2MEXvY4k5cE) I would rather remove `kind projector` for the moment.
> remove kind projector (limited usage + intellij issue)

- docs/src/main/tut/lens.md
`Lens[S, A].apply` requires `A => S => S` as the second argument
So, `(p => a => p.copy...)` should be `(a => p => p.copy...)`
> Fix typo in lens.md

- example/src/test/scala/monocle/HttpRequestExample.scala
I'v implemented the `HttpRequest` example used in [Beyond scala Lens](http://www.slideshare.net/JulienTruffaut/beyond-scala-lens)
This example shows 
- how to use `GenPrism` to create `Prism` with case object. I found #219 but it seems outdated. (`GenIso.obj` instead of `GenIso.unit`) 
```scala
sealed trait HttpMethod
case object GET   extends HttpMethod
case object POST  extends HttpMethod
val get: Prism[HttpMethod, Unit] = GenPrism[HttpMethod, GET.type] composeIso GenIso.unit[GET.type]
val post = GenPrism[HttpMethod, POST.type] composeIso GenIso.unit[POST.type]
```
- how to use `at` and `index` to achieve the same result, and how they are different
- `Gen*` macro, `filterIndex` usage
> Add HttpRequestExample.scala

- example/src/test/scala/monocle/LensExample.scala
- macro/src/main/scala/monocle/macros/Lenses.scala
- macro/src/main/scala/monocle/macros/internal/Macro.scala
Here, `@Lenses` is changed to generate polymorphic lenses for case classes with type parameters. Generated lenses are polymorphic in types that are used by corresponding field (and only by it) and types that aren't used by any field. For example:
```
case class Foo[A, B, C](x: (A, B), y: B => Double)
```
will have the following lenses generated:
```
def x[A, B, C, A$, C$] = new PLens[Foo[A, B, C], Foo[A$, B, C$], (A, B), (A$, B)]{ … }
def y[A, B, C, C$] = new PLens[Foo[A, B, C], Foo[A, B, C$], B => Double, B => Double]{ … }
```
> Fix #114: generate polymorphic lenses

- core/src/main/scala/monocle/std/Vector.scala
Current implementation of indexed updates for Vector seems to be doing a full traversal and copy, which is O(n) or worse and also bypasses the nice persistent sharing properties of Vector. This small patch uses Vector.updated, which enables structural sharing and much lower time complexity.
> Use Vector.updated for efficient, persistent indexed vector updates

- core/src/main/scala/monocle/std/Vector.scala
vectorIndex: use isDefinedAt instead of catching an exception.
As agreed apon in #285.
> vectorIndex: use isDefinedAt instead of catching an exception

- core/src/main/scala/monocle/std/All.scala
- core/src/main/scala/monocle/std/Cofree.scala
- test/src/test/scala/monocle/TestInstances.scala
- test/src/test/scala/monocle/std/CofreeSpec.scala
For https://github.com/julien-truffaut/Monocle/issues/177
> WIP - Cofree Optics

- build.sbt
- example/src/test/scala/monocle/function/AtExample.scala
- refine/src/main/scala/monocle/refine/All.scala
- refined/src/main/scala/monocle/refined/All.scala
- refined/src/main/scala/monocle/refined/bits.scala
- refined/src/main/scala/monocle/refined/internal/Bits.scala
- refined/src/main/scala/monocle/refined/package.scala
- test/src/test/scala/monocle/MonocleSuite.scala
- test/src/test/scala/monocle/refined/BitsSpec.scala
It seems that this doesn't cause any problems in `AtExample.scala` where we have both imports:
```scala
import eu.timepit.refined._
import monocle.refined._
```
> Rename subproject and package to refined

- bench/src/main/scala/monocle/bench/ProductIsoBench.scala
- build.sbt
- macro/src/main/scala/monocle/macros/GenIso.scala
- project/plugins.sbt
- test/src/test/scala/other/MacroOutSideMonocleSpec.scala
Addresses #295.
Included is a benchmark for comparison with `productToTuple`.
I also took the liberty of upgrading JMH from 0.2.4 to 0.2.5 while I was there. Hope that's ok.
> Add GenIso.fields

- core/src/main/scala/monocle/function/Plated.scala
before:
```scala
scala> monocle.function.Plated.children(100)
<console>:11: error: Could not find an instance of Plated[{A}], please check Monocle instance location policy to find out which import is necessary
monocle.function.Plated.children(100)
^
```
after:
```scala
scala> monocle.function.Plated.children(100)
<console>:11: error: Could not find an instance of Plated[Int], please check Monocle instance location policy to find out which import is necessary
monocle.function.Plated.children(100)
^
```
> fix implicitNotFound message of Plated

- .travis.yml
Monocle repos seems to use not container-based infrastructure but standard infrastructure on Travis CI build job.
So I added `sudo: false` explicitly.
There is advantages that:
* build faster
* cache available (despite public repos)
ref: https://docs.travis-ci.com/user/workers/container-based-infrastructure/
> Using container-based infrastructure on Travis CI build job

- docs/src/site/typeclasses.md
> Cats documentation has moved to Typelevel.org

- core/shared/src/main/scala/monocle/std/String.scala
- test/shared/src/test/scala/monocle/RegressionSpec.scala
For String-to-Long Prism and derivatives (String-to-Int, String-to-Byte)
> Fix #336 (partially) Add logic to exclude unlawful Strings 

- core/shared/src/main/scala/monocle/std/String.scala
- test/shared/src/test/scala/monocle/RegressionSpec.scala
This PR makes the String to Boolean Prism to respect Prism laws by constraining the string input to only be lowercase.
This also removes the usage of Scalaz's Disjunction since Exceptions are not being raised any more.
> 336 - stringToBoolean to respect Prism laws

- core/shared/src/main/scala/monocle/function/At.scala
- example/src/test/scala/monocle/function/AtExample.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
Add function 'sans' to delete a value associated with a key in a Map-like container.
> Add sans to At

- build.sbt
- law/shared/src/main/scala/monocle/law/discipline/LensTests.scala
- law/shared/src/main/scala/monocle/law/discipline/OptionalTests.scala
- law/shared/src/main/scala/monocle/law/discipline/function/AtTests.scala
- law/shared/src/main/scala/monocle/law/discipline/function/IndexTests.scala
- refined/shared/src/main/scala/monocle/refined/internal/Bits.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
- test/shared/src/test/scala/monocle/function/IndexSpec.scala
- test/shared/src/test/scala/monocle/refined/BitsSpec.scala
- test/shared/src/test/scala/monocle/std/IMapSpec.scala
- test/shared/src/test/scala/monocle/std/ISetSpec.scala
- test/shared/src/test/scala/monocle/std/ListSpec.scala
- test/shared/src/test/scala/monocle/std/MapSpec.scala
- test/shared/src/test/scala/monocle/std/NonEmptyListSpec.scala
- test/shared/src/test/scala/monocle/std/OneAndSpec.scala
- test/shared/src/test/scala/monocle/std/SetSpec.scala
- test/shared/src/test/scala/monocle/std/StreamSpec.scala
- test/shared/src/test/scala/monocle/std/StringSpec.scala
- test/shared/src/test/scala/monocle/std/VectorSpec.scala
Fix issue in Bits where singleBit for Long was shitfing bits incorrectly
Add random index for IndexTests/OptionalTests using ScalaCheck
> Fix #315 #342

- generic/shared/src/main/scala/monocle/generic/Product.scala
- test/shared/src/test/scala/monocle/generic/ProductSpec.scala
Implement a generic `Each` instance for any product tuple and case class which wraps all entities of the same type using shapeless typeclass derivation.
I didn't put the tests in `TupleNSpec` because I realised after leaving the hack-day that this would have worked with any product type, including case classes.
> Introduce generic Each derivation

- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Prism.scala
- test/shared/src/test/scala/monocle/Arities.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
We use this at @slamdata to avoid having to deal with various inference problems caused by subtyping. @wemrysi came up with this approach.
> Treat PPrisms as smart constructors for type T.

- core/shared/src/main/scala/monocle/Prism.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
A helper for construction of Prisms that shortens their definitions
slightly. Very helpful when you have dozens of them strewn across your
codebase.
We use this a lot at @slamdata. Here’s a recently-added batch: https://github.com/sellout/quasar/blob/modernize-sql-expr/core/src/main/scala/quasar/sql/package.scala#L31
> Prism.partial uses a PartialFunction rather than Option.

- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Prism.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
Fixes #360.
The goal here is to be able to use arbitrary Prisms and Isos as
apply/unapply objects, making the relationship between apply/unapply
more explicit.
> Add unapply method to PPrism and PIso.

- example/src/test/scala/monocle/state/StateExample.scala
- state/shared/src/main/scala/monocle/state/All.scala
- state/shared/src/main/scala/monocle/state/StateOptionalSyntax.scala
- test/shared/src/test/scala/monocle/MonocleSuite.scala
Similar to what was already available for Lens.
I'm not sure how useful this is to anyone apart from me, so feel free to reject this PR.
My use case for this is concisely chaining JSON transformations using `JsonPath` in Circe.
e.g. if I have some input JSON
```scala
val inputJson = parse("""
{
"user": {
"name": "Chris",
"age": 31
},
"timestamp": 1470326934000
}
""").getOrElse(Json.Null)
```
then I could transform it as follows:
```scala
val transform = for {
_ <- root.user.name.string mod (_.toLowerCase)
_ <- root.user.age.int mod (_ + 1)
x <- root.timestamp.long mod (new DateTime(_).toString)
} yield x
val transformedJson = transform.exec(inputJson)
```
> Add State syntax for Optional

- PROCESS.md
This is in order to avoid holding a PR for too long. A PR can always be reverted or edited at a further date.
> Add an exception to the PR signoff

- docs/src/site/_config.yml
- docs/src/site/css/styles.css
my local preview
```bash
$ cd docs/src/site/
$ jekyll serve
```
Before:
After:
> fix table rendering in docs

- core/shared/src/main/scala/monocle/function/Index.scala
I quickly benchmark it and it seems to improve update performance by at least 50% when the index is within the list.
> improve performance of index List and Stream instances

- example/src/test/scala/monocle/state/ReaderExample.scala
- example/src/test/scala/monocle/state/StateExample.scala
- state/shared/src/main/scala/monocle/state/All.scala
- state/shared/src/main/scala/monocle/state/ReaderGetterSyntax.scala
- state/shared/src/main/scala/monocle/state/StateGetterSyntax.scala
- state/shared/src/main/scala/monocle/state/StateLensSyntax.scala
- state/shared/src/main/scala/monocle/state/StateOptionalSyntax.scala
- state/shared/src/main/scala/monocle/state/StateSetterSyntax.scala
- test/shared/src/test/scala/monocle/MonocleSuite.scala
This PR contains some changes in the peripheral modules:
* It includes new methods (`extract`, `extracts`, `assign_` and `mod_`) for the existing lens and optional representatives in the state module.
* It adds new representatives in the state module, such as `Getter` and `Setter`.
* It adds a new *reader* module, which includes a `Getter` representative as example.
In general, these ideas have emerged while writing a blog post, ["Lens, State Is Your Father"](https://blog.hablapps.com/2016/11/10/lens-state-is-your-father/), where they are described in detail.
> extend peripheral modules

- docs/src/main/tut/getting_started.md
- docs/src/main/tut/release_notes.md
- version.sbt
The main goal of this milestone release is to let users test the refactor of typeclass https://github.com/julien-truffaut/Monocle/pull/405.
I will release tomorrow if everything is ok.
> prepare 1.4.0-M1 release

- core/shared/src/main/scala/monocle/Getter.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
As per [Gitter](https://gitter.im/julien-truffaut/Monocle?at=5853cf11c895451b75e2a6f9) this is `.zip` for Getter.  
@julien-truffaut I looked at `.zip` for `Fold` as well, but I must admit that the implementation wasn't immediately obvious to me, and I didn't have the time to think about it yet.  I'll get back to it when I've got more time.  Would appreciate pointers in the right direction :blush:
> Add .zip to Getter

- core/shared/src/main/scala/monocle/Getter.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
Closes GH-455
@julien-truffaut While I was at it :)
> Add unzip instance for Getter

- core/shared/src/main/scala/monocle/function/All.scala
- core/shared/src/main/scala/monocle/function/Possible.scala
- core/shared/src/main/scala/monocle/std/All.scala
- core/shared/src/main/scala/monocle/std/Try.scala
- law/shared/src/main/scala/monocle/law/discipline/function/PossibleTests.scala
- test/shared/src/test/scala/monocle/function/PossibleSpec.scala
- test/shared/src/test/scala/monocle/std/DisjunctionSpec.scala
- test/shared/src/test/scala/monocle/std/EitherSpec.scala
- test/shared/src/test/scala/monocle/std/MaybeSpec.scala
- test/shared/src/test/scala/monocle/std/OptionSpec.scala
- test/shared/src/test/scala/monocle/std/TrySpec.scala
- test/shared/src/test/scala/monocle/std/ValidationSpec.scala
As discussed in #450.
The code is basically a facsimile of the `Each` code, with `Optional` instead of `Traversal`, and instances for `Option`, `Either`, `\/`, `Validation` and `Maybe`.  I've omitted support for `scala.util.Try`, which should probably have its own file in `std`, and would be better presented as a separate PR.
The property based test follows `Each` in using the `fromIso` method as a vehicle for hitching the concept to the `Optional` laws.  
I haven't added anything special for `possible.asTraversable == each`, because it concerns types that have both `Each` and `Possible` instances, which only `Maybe` currently satisfies, and possibly warrants further conversation.   
It would be technically correct to make `Possible` a subclass of `Each` (ie every `Possible` yields a …
> New `Possible` typeclass that defines a canonical Optional over a type

- refined/shared/src/main/scala/monocle/refined/chars.scala
- refined/shared/src/main/scala/monocle/refined/package.scala
- refined/shared/src/main/scala/monocle/refined/strings.scala
This uses `refinedPrism` (which was added in #483) to implement
`chars.lowerCase` and `chars.upperCase`.
> Use refinedPrism to implement chars prisms

- .travis.yml
```yaml
env:
sudo: false
```
is no effect. Right way is
```yaml
sudo: false
```
but if set `sudo: false` scala-js tests failure.
> set sudo: true

- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/syntax/All.scala
- core/shared/src/main/scala/monocle/syntax/Traversal.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
This includes an alternative constructor for lenses based on `Store` coalgebras. In fact, this constructor is even more generic, since it uses the `StoreComonad` typeclass, where `pos` and `peek` can be found.
(*) Similar constructors could be included for `PLens` (`S => IndexedStore[A, B, T]`), `Traversal` (`S => FreeAp[Store[A, ?], S]`) and `PTraversal` (`S => FreeAp[IndexedStore[A, B, T]]`).
> Adds coalgebroid-based constructors for Lens and Traversal

- .travis.yml
- build.sbt
- core/native/src/main/scala/monocle/std/PlatformSpecificString.scala
- project/plugins.sbt
- testNative/src/main/scala/monocle/Main.scala
first support: core, state
```
> show coreNative/nativeMissingDependencies
[info] * @java.net.URI
[info] * @java.net.URI::init_class.java.lang.String
[info] * @java.net.URI::toString_class.java.lang.String
[success] Total time: 4 s, completed 2017/03/17 0:27:58
> show stateNative/nativeMissingDependencies
[info] *
[success] Total time: 1 s, completed 2017/03/17 0:28:05
> show testNative/nativeMissingDependencies
[info] *
[success] Total time: 1 s, completed 2017/03/17 0:28:16
```
we need remove `java.net.URI` ...? :thinking:  /cc @densh @MasseGuillaume
https://github.com/julien-truffaut/Monocle/blob/v1.4.0/core/shared/src/main/scala/monocle/std/String.scala#L35-L36
> support Scala Native

- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/function/FilterIndex.scala
- core/shared/src/main/scala/monocle/function/Plated.scala
- core/shared/src/main/scala/monocle/law/IsoLaws.scala
- core/shared/src/main/scala/monocle/law/LensLaws.scala
- core/shared/src/main/scala/monocle/law/OptionalLaws.scala
- core/shared/src/main/scala/monocle/law/PrismLaws.scala
- core/shared/src/main/scala/monocle/syntax/Traversal.scala
- example/src/test/scala/monocle/JsonExample.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/function/PlatedSpec.scala
`pure` is also used in Cats, so it reduces the diffs between Scalaz and Cats branches.
> Prefer `pure` over `point`.

- .travis.yml
ref. https://github.com/travis-ci/travis-ci/issues/7703 
https://travis-ci.org/aoiroaoino/Monocle/jobs/229362123
```
$ sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/$PRE
/home/travis/.travis/job_stages: line 53: /usr/local/bin/sbt: Permission denied
The command "sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/$PRE" exited with 126.
0.00s$ sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/test packageSrc
/home/travis/.travis/job_stages: line 53: /usr/local/bin/sbt: Permission denied
https://github.com/travis-ci/travis-ci/issues/7703
```
> workaround for travis-ci bug

- build.sbt
- test/shared/src/test/scala/monocle/refined/BitsSpec.scala
- test/shared/src/test/scala/monocle/refined/CharSpec.scala
- test/shared/src/test/scala/monocle/refined/StringsSpec.scala
This also makes use of refined-scalacheck instances in tests.
> Update to refined 0.8.2

- example/src/test/scala/monocle/state/StateExample.scala
- state/shared/src/main/scala/monocle/state/All.scala
- state/shared/src/main/scala/monocle/state/StateTraversalSyntax.scala
- test/shared/src/test/scala/monocle/MonocleSuite.scala
Adds syntax for `Traversal`s in the state module, including `extract`, `mod`, `assign` and related methods.
> Add state syntax for traversal

- bench/src/main/scala/monocle/bench/BenchModel.scala
- bench/src/main/scala/monocle/bench/MonocleTraversalBench.scala
- build.sbt
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/function/At.scala
- core/shared/src/main/scala/monocle/function/Each.scala
- core/shared/src/main/scala/monocle/function/Empty.scala
- core/shared/src/main/scala/monocle/function/FilterIndex.scala
- core/shared/src/main/scala/monocle/function/Index.scala
- example/src/test/scala/monocle/HttpRequestExample.scala
- example/src/test/scala/monocle/JsonExample.scala
- example/src/test/scala/monocle/function/AtExample.scala
- example/src/test/scala/monocle/function/EachExample.scala
- example/src/test/scala/monocle/function/EmptyExample.scala
- example/src/test/scala/monocle/function/FilterIndexExample.scala
- example/src/test/scala/monocle/function/IndexExample.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
- test/shared/src/test/scala/monocle/function/Data.scala
- test/shared/src/test/scala/monocle/function/FilterIndexSpec.scala
- test/shared/src/test/scala/monocle/function/IndexSpec.scala
- test/shared/src/test/scala/monocle/std/MapSpec.scala
- test/shared/src/test/scala/other/MacroOutSideMonocleSpec.scala
This updates Monocle to cats-1.0.0-RC1.
The only real change is `Map` → `SortedMap` everywhere, which is a hassle but is mostly mechanical. The other option would be to pull in alley-cats but personally I'd prefer to relegate those instances to a `monocle-alleycats` or something and keep the core lawful.
I deleted the aliased `IList` and `IMap` examples but left the rename imports like `{ Monoidal => Zip }`. If you'd like to get rid of these and other scalaz cruft I can do it here or in another PR.
> cats 1.0.0-RC1

- .travis.yml
- build.sbt
- enable laws project compile with Scala 2.13.0-M4
- update discipline, refined, scalacheck and scalatest
- drop Scala 2.10. discipline 0.10.0 does not support Scala 2.10
> update dependencies. drop Scala 2.10

- example/src/test/scala/monocle/generic/CoproductExample.scala
- generic/shared/src/main/scala/monocle/generic/All.scala
- generic/shared/src/main/scala/monocle/generic/CoProduct.scala
- generic/shared/src/main/scala/monocle/generic/Generic.scala
- generic/shared/src/main/scala/monocle/generic/internal/CoproductToDisjunction.scala
- generic/shared/src/main/scala/monocle/generic/internal/DisjunctionToCoproduct.scala
- test/shared/src/test/scala/monocle/generic/CoproductSpec.scala
As discussed in the gitter channel, this PR adds an isomorphism between sum types (`shapeless.Coproduct`) and the disjunction of their parts.
If we have the following coproduct:
```scala
type ISB = Int :+: String :+: Boolean :+: CNil
```
We can use `coProductIso`/`coProductDisjunctionIso` to obtain the following isomorphisms:
```scala
val iso: Iso[ISB, Either[Int, Either[String, Boolean]]] = coProductIso[ISB].apply
val iso: Iso[ISB, Int \/ (String \/ Boolean)] = coProductDisjunctionIso[ISB].apply
```
One use case where this is useful, is when every case class that extends a sealed trait has a common field, and you want to zoom in on it.
```scala
sealed trait X
case class A(name: String) extends X
case class B(name: String) extends X
case class C(name: String) extends X
val lens: Lens[X, …
```
> Added `coProductIso`/`coProductDisjunctionIso` and `GenericOptics`

- macro/shared/src/main/scala/monocle/macros/GenIso.scala
- macro/shared/src/main/scala/monocle/macros/GenPrism.scala
- macro/shared/src/main/scala/monocle/macros/internal/Macro.scala
It's a good and safe practice to add the override modifier to all overriding members.
Brought on by [wartremover-contrib's MissingOverride](https://github.com/wartremover/wartremover-contrib#missingoverride) triggering for the macro expansion of lenses.
> Added Override Modifiers

- core/shared/src/main/scala/monocle/function/Cons.scala
- core/shared/src/main/scala/monocle/function/Cons1.scala
- core/shared/src/main/scala/monocle/function/Each.scala
- core/shared/src/main/scala/monocle/function/Empty.scala
- core/shared/src/main/scala/monocle/function/FilterIndex.scala
- core/shared/src/main/scala/monocle/function/Index.scala
- core/shared/src/main/scala/monocle/function/Plated.scala
- core/shared/src/main/scala/monocle/function/Reverse.scala
- core/shared/src/main/scala/monocle/function/Snoc.scala
- core/shared/src/main/scala/monocle/function/Snoc1.scala
- core/shared/src/main/scala/monocle/std/All.scala
- core/shared/src/main/scala/monocle/std/Chain.scala
- core/shared/src/main/scala/monocle/std/NonEmptyChain.scala
- test/shared/src/test/scala/monocle/TestInstances.scala
- test/shared/src/test/scala/monocle/std/ChainSpec.scala
- test/shared/src/test/scala/monocle/std/CofreeSpec.scala
- test/shared/src/test/scala/monocle/std/NonEmptyChainSpec.scala
- test/shared/src/test/scala/monocle/std/NonEmptyListSpec.scala
- test/shared/src/test/scala/monocle/std/NonEmptyVectorSpec.scala
- test/shared/src/test/scala/monocle/std/OneAndSpec.scala
- test/shared/src/test/scala/monocle/std/TheseSpec.scala
- test/shared/src/test/scala/monocle/std/ValidationSpec.scala
`Chain` doesn't have methods like `drop` and `updated` like lists do, so some of these implementations are a bit more verbose.
Also: deleted instances for cats' data types from `TestInstances`, and used the pre-defined instances from `import cats.laws.discipline.arbitrary._` instead.
> Add optics for `cats.data.Chain` / `NonEmptyChain`

- .travis.yml
- example/src/test/scala/monocle/state/StateExample.scala
- state/shared/src/main/scala/monocle/state/All.scala
- state/shared/src/main/scala/monocle/state/StateLensSyntax.scala
- state/shared/src/main/scala/monocle/state/StateOptionalSyntax.scala
- state/shared/src/main/scala/monocle/state/StateSetterSyntax.scala
- test/shared/src/test/scala/monocle/MonocleSuite.scala
The syntax can be simplified once https://github.com/typelevel/cats/issues/2686 if fixed
`StateTraversalSyntax` can be tested (therefore ported) once https://github.com/typelevel/cats/issues/2687 is fixed
> Add missing function to State module (fixes #548)

- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/internal/IsEq.scala
- core/shared/src/main/scala/monocle/syntax/Apply.scala
- example/src/test/scala/monocle/LensExample.scala
- macro/shared/src/main/scala/monocle/macros/syntax/GenApplyLensSyntax.scala
- state/shared/src/main/scala/monocle/state/ReaderGetterSyntax.scala
- state/shared/src/main/scala/monocle/state/StateGetterSyntax.scala
- state/shared/src/main/scala/monocle/state/StateLensSyntax.scala
- state/shared/src/main/scala/monocle/state/StateOptionalSyntax.scala
- state/shared/src/main/scala/monocle/state/StateSetterSyntax.scala
- state/shared/src/main/scala/monocle/state/StateTraversalSyntax.scala
This PR fixes a collision when we use something like [scala-newtype](https://github.com/estatico/scala-newtype) and have `import monocle.macros.syntax.lens._` in scope.  A cause of collision is `val value: A` in `GenApplyLensOps` so it conflicts with any `.value` that is defined via implicit syntax. The same issue was fixed in Cats code base - see https://github.com/typelevel/cats/issues/2491 and 
https://github.com/typelevel/cats/pull/2614.
Proposed change can be considered as binary compatible - unless someone used `GenApplyLensOps.value` in code which is unlikely. We can probably do a bit more and replace  `toGenApplyLensOps` and `GenApplyLensOps` with single implicit class - as Scala looks to be not instantiating it for macro based syntax. But this change can break some code using …
> Fix implicit syntax collisions

- build.sbt
- "-Xfuture" is deprecated since Scala 2.13 https://github.com/scala/scala/commit/67195a5cffadac9340b3228ee804e01a0fc02e25
- "-Ywarn-unused-import" is replaced by "-Ywarn-unused:imports" since Scala 2.12
> fix scalacOptions

- .gitignore
- core/shared/src/main/scala/monocle/function/Cons.scala
- generic/shared/src/main/scala/monocle/generic/Product.scala
So I realised that in order to implement fixes that aren't backwards compatible we are going to have to duplicate at least significant portions of the code base, if not all of it.  It's probably not a price you are willing to pay, understandably.  Hence only the ones (2 of them!) with a backwards compatible fix have been added.
> Issue 649 d

- build.sbt
- project/build.properties
it would helpful in the Scala community build to have this merged,
normally we can override org changes like this in our config, but I'm
having trouble I don't understand. and anyway, using the latest
versions is generally a good thing
the sbt bump isn't a necessary part of this, but it may help avert
unexpected community build trouble as well
> kind-projector org change (and sbt version bump)

- CODE_OF_CONDUCT.md
Typelevel is [switching to the Scala Code of Conduct](https://typelevel.org/blog/2019/05/01/typelevel-switches-to-scala-code-of-conduct.html), and encourages all member projects to adopt it.
> Add Scala Code of Conduct

- build.sbt
- project/plugins.sbt
I think sbt-release isn't needed and could be removed. This assumes we have a single common version which I think is true for monocle.
Note the `jsEnv` setting set in the build is now the default in scala.js and can be removed
> Remove sbt-release

- kernel/shared/src/main/scala/monocle/Lens.scala
- kernel/shared/src/main/scala/monocle/Optional.scala
- kernel/shared/src/main/scala/monocle/function/At.scala
- kernel/shared/src/main/scala/monocle/function/Cons.scala
- kernel/shared/src/main/scala/monocle/function/Index.scala
- I used the same encoding as for `FieldX` and `Cons`.
- Introduced inheritance between `At` and `Index`
- I wonder if we should have an `AtK` version for higher kinded `S`, e.g. `Atk[List, Int]` instead of `At[List[A], Int, A]`
> At - Index typeclass

- core/shared/src/main/scala/monocle/function/Index.scala
- test/shared/src/test/scala/monocle/function/IndexSpec.scala
This adds a missing instance of `Index` for `ListMap` and should fix compilation errors like the one below.
```
[error] ...: ambiguous implicit values:
[error]  both method mapIndex in object Index of type [K, V]=> monocle.function.Index[Map[K,V],K,V]
[error]  and method sortedMapIndex in object Index of type [K, V]=> monocle.function.Index[scala.collection.immutable.SortedMap[K,V],K,V]
[error]  match expected type monocle.function.Index[S,String,A]
```
> Missing instance of Index for ListMap

- macro/src/main/scala/monocle/macros/internal/Macro.scala
- macro/src/test/scala/monocle/LensGenSpec.scala
Small fix to the GenLens macro to support `_.foo.bar`.
The generated code now calls `Lens#compose` (which returns a `Lens`) instead of `Optional#composeLens` (which returns an `Optional`).
> Fix chained field selection in macro

- core/shared/src/main/scala/monocle/Traversal.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
This relates to `PTraversal.modifyF` like `Parallel.parTraverse` relates to `Traverse.traverse`.
It's easy to define `parModifyF` for `PLenses`, `PPrism`s and `POptional`s, but I don't see the need for it yet.
> Add PTraversal.parModifyF

- core/shared/src/main/scala/monocle/std/BigDecimal.scala
- docs/src/main/tut/release_notes.md
Should be non-semantic.
Uses https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines to find likely typos.
> Fix spelling typos

- .github/workflows/scala.yml
It is better to use sbt directly to check for format correctness. The action I used earlier is not actively maintained
This version uses sbt and maybe a bit slower but will support upgrades better
> Check scalafmt directly with sbt

- macro/src/main/scala/monocle/macros/internal/Macro.scala
> stop importing cats.Functor in gen lens macros

- .travis.yml
- build.sbt
I am trying to verify binary compatibility for https://github.com/julien-truffaut/Monocle/issues/794
I don't understand why mima reports lost of changes in `monocle.std.nev`. As far as I can tell, we haven't changed that file: https://github.com/julien-truffaut/Monocle/compare/v2.0.0...master
here is an example:
```
[error]  * method vectorToNev()monocle.PPrism in object monocle.std.nev has a different signature in current version, where it is <A:Ljava/lang/Object;>()Lmonocle/PPrism<Lscala/collection/immutable/Vector<TA;>;Lscala/collection/immutable/Vector<TA;>;Lcats/data/NonEmptyVector<TA;>;Lcats/data/NonEmptyVector<TA;>;>; rather than <A:Ljava/lang/Object;>()Lmonocle/PPrism<Lscala/collection/immutable/Vector<TA;>;Lscala/collection/immutable/Vector<TA;>;Lscala/collection/immutable/Vector< …
```
> bump mima previos version to 2.0.0

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/function/At.scala
- core/shared/src/main/scala/monocle/function/Cons.scala
- core/shared/src/main/scala/monocle/function/Field.scala
- core/shared/src/main/scala/monocle/function/Index.scala
- core/shared/src/main/scala/monocle/function/Possible.scala
- core/shared/src/main/scala/monocle/function/Reverse.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedFold.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedGetter.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedIso.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedLens.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedOptional.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedPrism.scala
- dotSyntax/src/main/scala/monocle/syntax/AppliedSetter.scala
- dotSyntax/src/main/scala/monocle/syntax/applied.scala
- dotSyntax/src/main/scala/monocle/syntax/fold.scala
- dotSyntax/src/main/scala/monocle/syntax/getter.scala
- dotSyntax/src/main/scala/monocle/syntax/iso.scala
- dotSyntax/src/main/scala/monocle/syntax/lens.scala
- dotSyntax/src/main/scala/monocle/syntax/optional.scala
- dotSyntax/src/main/scala/monocle/syntax/prism.scala
- dotSyntax/src/main/scala/monocle/syntax/setter.scala
- generic/src/main/scala/monocle/generic/CoProduct.scala
This PR renames the type parameters in optics from `A`, `B` to `From` and `To`, e.g.
```scala
trait Lens[From, To] {
def get(from: From): To
def set(to: To): From => From
}
```
I believe it should make the code more readable, especially for beginners.
> Friendly type paramaters

- docs/src/main/tut/index.md
People who are not familiar with macros might wonder why macro paradise doesn't work on 2.13 and what to do instead, so I think it's worth a little hint.
> Add macro hint for Scala 2.13

- .travis.yml
We should clean before releasing for 0.6.32 or it would not recompile
> Clean before release

- build.sbt
Disables fatal warnings on core to workaround https://github.com/sbt/zinc/issues/688
> Workaround to build with sbt 1.3.x

- docs/src/main/mdoc/unsafe_module.md
- test/shared/src/test/scala/monocle/unsafe/MapTraversalSpec.scala
- unsafe/src/main/scala/monocle/unsafe/MapTraversal.scala
I have a use case in which I need to rename the key of a json object, i.e. rename "_key" to "key".
I am pretty sure that I will not create any key collision. In my use case, creating unsafe instances of `Iso[Map[K,V], List([K, V])]` and `Traversal[Map[K, V], (K, V)]` is useful.
> add unsafe Iso[Map[K,V], List([K, V])] and Traversal[Map[K, V], (K, V)]

- core/shared/src/main/scala/monocle/Iso.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
I took a quick stab at #868
I wasn't entirely sure whether `involuted` (I decided to pick that as opposed to `involution` to be consistent with [haskell](https://hackage.haskell.org/package/lens-4.19.2/docs/src/Control.Lens.Iso.html#involuted)) should live on the `Iso` object or somewhere else, happy to change it if we think it's better placed elsewhere.
> Add Iso involuton

- .github/workflows/release.yml
- .github/workflows/scala.yml
- build.sbt
- core/shared/src/main/scala/monocle/function/Index.scala
This PR updates scala and the versions of discipline used in the project
discipline is no longer published for scala.js 0.6.x so we need to follow suit
> Upgrade discipline and scala

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- test/shared/src/test/scala/monocle/FoldSpec.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
Inspired by Haskell lens' `to :: (Profunctor p, Contravariant f) => (s -> a) -> Optic' p f s a ` which builds a `Getter` from an arbitrary function.
> Lift arbitrary functions to Getters

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/function/At.scala
- core/shared/src/main/scala/monocle/syntax/Apply.scala
- example/src/test/scala/monocle/function/AtExample.scala
- test/shared/src/test/scala/monocle/FoldSpec.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/SetterSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
- test/shared/src/test/scala/monocle/std/OptionSpec.scala
The two most common operations on optics that point to an `Option` are:
1. focus only on `Some` which we can do with `some`
1. focus on `Some` or replace `None` by some default value
I propose to add `withDefault` method to all optics and apply optics similar to what we've done for `some`.
I removed `atOrElse`, it can easily be achieved by `at(x).withDefault(y)`
Main questions:
1. Is this use case worth the maintenace cost?
1. shall we add syntax for monorphic optics somewhere else? `implicit evTS: T =:= S, evBA: B =:= A, evOpt: A =:= Option[A1]` is not really readable.
> Replace atOrElse by withDefault syntax on optics

- build.sbt
- core/jvm/src/main/scala/monocle/std/PlatformSpecificString.scala
- core/shared/src/main/scala/monocle/function/Cons.scala
- core/shared/src/main/scala/monocle/function/Curry.scala
- core/shared/src/main/scala/monocle/function/Reverse.scala
- core/shared/src/main/scala/monocle/function/Snoc1.scala
- core/shared/src/main/scala/monocle/internal/Bounded.scala
- core/shared/src/main/scala/monocle/std/String.scala
- core/shared/src/main/scala/monocle/syntax/Apply.scala
- core/shared/src/main/scala/monocle/syntax/ApplyIso.scala
- project/plugins.sbt
This PR allows to cross compile the core module to `dotty` and scala `2.13.3`
It works locally but I had some problems with the `doc` task on GH actions
Fixes #925
> Crosscompile core to dotty

- build.sbt
Another attempt, this switches to the latest doc tool for dotty but still fails. Instead we just skip building dotty docs altogether.
> Skip building docs in dotty

- docs/src/main/mdoc/optics.md
- website/pages/en/index.js
The links on the landing page to the documentation seemed to be broken. I've really no idea what I'm doing here, but locally this appears to fix it. Hope it's okay to send unsolicited PRs. Feel free to close, ignore and reinterpret as a bug report if not :slightly_smiling_face:
> Fix links to docs and class-diagram on website

- build.sbt
This may fix the release failing task.
I'm disabling publishing for dotty, it is recommended not to publish with dependencies from scala 2. Though the code compiles and tests run it may cause dependency issues downstream
> Fix doc task and skip publishing dotty for now

- .github/workflows/release.yml
- .github/workflows/scala.yml
These need to be upgraded ASAP as github deprecated some api calls
> Upgrade obsolete github actions

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/syntax/ApplyFold.scala
- core/shared/src/main/scala/monocle/syntax/ApplyGetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyIso.scala
- core/shared/src/main/scala/monocle/syntax/ApplyLens.scala
- core/shared/src/main/scala/monocle/syntax/ApplyOptional.scala
- core/shared/src/main/scala/monocle/syntax/ApplyPrism.scala
- core/shared/src/main/scala/monocle/syntax/ApplySetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyTraversal.scala
- docs/src/main/mdoc/examples/university_example.md
- docs/src/main/mdoc/faq.md
- docs/src/main/mdoc/optics/lens.md
- docs/src/main/mdoc/optics/prism.md
- docs/src/main/mdoc/unsafe_module.md
- example/src/test/scala/monocle/ComposeIssueExample.scala
- example/src/test/scala/monocle/HttpRequestExample.scala
- example/src/test/scala/monocle/JsonExample.scala
- example/src/test/scala/monocle/LensExample.scala
- example/src/test/scala/monocle/generic/CoproductExample.scala
- macro/src/main/scala/monocle/macros/internal/Macro.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/std/OptionSpec.scala
- test/shared/src/test/scala/monocle/unsafe/UnsafeSelectSpec.scala
see #964
I believe we can deprecate all `composeX` methods once we have a short cut for `at`, `index` and maybe a few other common optics.
> add andThen on all optics

- build.sbt
- core/shared/src/main/scala/monocle/function/All.scala
- core/shared/src/main/scala/monocle/function/At.scala
- core/shared/src/main/scala/monocle/function/Cons.scala
- core/shared/src/main/scala/monocle/function/Cons1.scala
- core/shared/src/main/scala/monocle/function/Field1.scala
- core/shared/src/main/scala/monocle/function/Field2.scala
- core/shared/src/main/scala/monocle/function/Field3.scala
- core/shared/src/main/scala/monocle/function/Field4.scala
- core/shared/src/main/scala/monocle/function/Field5.scala
- core/shared/src/main/scala/monocle/function/Field6.scala
- core/shared/src/main/scala/monocle/function/Snoc.scala
- core/shared/src/main/scala/monocle/function/Snoc1.scala
- core/shared/src/main/scala/monocle/syntax/Fields.scala
- example/src/test/scala/monocle/function/FieldsExample.scala
- example/src/test/scala/monocle/generic/HListExample.scala
- example/src/test/scala/other/ImportExample.scala
- law/src/main/scala/monocle/law/discipline/function/AtTests.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
- test/shared/src/test/scala/monocle/generic/HListSpec.scala
- test/shared/src/test/scala/monocle/std/Tuple1Spec.scala
- test/shared/src/test/scala/monocle/std/Tuple2Spec.scala
- test/shared/src/test/scala/monocle/std/Tuple6Spec.scala
Thanks to @nafg for the idea! see #957 
If we like the idea, I would like to:
1. deprecate `First`, `Second`, etc
1. generate At instances for more tuples. Where shall we stop?
> Deprecate FieldX for At with a singleton index

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/function/Index.scala
- core/shared/src/main/scala/monocle/syntax/ApplyFold.scala
- core/shared/src/main/scala/monocle/syntax/ApplyGetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyIso.scala
- core/shared/src/main/scala/monocle/syntax/ApplyLens.scala
- core/shared/src/main/scala/monocle/syntax/ApplyOptional.scala
- core/shared/src/main/scala/monocle/syntax/ApplyPrism.scala
- core/shared/src/main/scala/monocle/syntax/ApplySetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyTraversal.scala
- test/shared/src/test/scala/monocle/FoldSpec.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/SetterSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
@julien-truffaut 
Closes #955, #956
> Add shortcuts for at, index

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/syntax/ApplyFold.scala
- core/shared/src/main/scala/monocle/syntax/ApplyGetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyIso.scala
- core/shared/src/main/scala/monocle/syntax/ApplyLens.scala
- core/shared/src/main/scala/monocle/syntax/ApplyOptional.scala
- core/shared/src/main/scala/monocle/syntax/ApplyPrism.scala
- core/shared/src/main/scala/monocle/syntax/ApplySetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyTraversal.scala
- test/shared/src/test/scala/monocle/FoldSpec.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/SetterSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
- test/shared/src/test/scala/monocle/unsafe/UnsafeSelectSpec.scala
- unsafe/src/main/scala/monocle/unsafe/UnsafeSelect.scala
This PR adds `Optional.filter` and `filter` method on all Optics and ApplyOptics.
`filter` allows to select the targets which satisfy a predicate, for example:
```scala
val positiveNumbers = Traversal.fromTraverse[List, Int].filter(_ > 0)
val list = List(1,2,-3,4,-5)
positiveNumbers.getAll(list) == List(1,2,4)
positiveNumbers.modify(_ * 10)(list) == List(10,20,-3,40,-5) // only the positive numbers are multiplied by 10
```
`filter` can break the fusion law that says that `modify(f).modify(g) == modify(f andThen g)`, for example:
```scala
val list       = List(1, 5, -3)
val firstStep  = positiveNumbers.modify(_ - 3)(list)            // List(-2, 2, -3)
val secondStep = positiveNumbers.modify(_ * 2)(firstStep)       // List(-2, 4, -3)
val bothSteps  = positiveNumbers.modify(x => (x - 3) * …
```
> add filter, deprecate unsafeSelect

- core/shared/src/main/scala/monocle/syntax/Apply.scala
- example/src/test/scala/monocle/function/AtExample.scala
- example/src/test/scala/monocle/function/EachExample.scala
- example/src/test/scala/monocle/function/FieldsExample.scala
- example/src/test/scala/monocle/function/FilterIndexExample.scala
- example/src/test/scala/monocle/function/IndexExample.scala
- test/shared/src/test/scala/monocle/FoldSpec.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/SetterSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
1. deprecate `applyX`, e.g. `applyLens`, `applyGetter`
2. deprecate symbolic aliases to `applyX` e.g. `&<->`
3. add `optics` method which transaform any value `a: A` into a `ApplyIso[A, A, A , A]` i.e. a partlially applied optics that points to itself
What do you think of `optics` name? it needs to be short.
> deprecate all applyX methods and operators in favor of optics method

- .gitignore
- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/AppliedFocusImpl.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/FocusImpl.scala
- core/shared/src/test/scala-3.x/monocle/focus/AppliedFocusTest.scala
Adds the fluent pre-applied syntax to the `Focus` macro, ie `address.focus(_.streetName)`, resolving #1027.
The solution uses the existing `monocle.syntax.ApplyXXX` classes.
> Focus macro pre-applied to object

- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/ErrorHandling.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/FocusBase.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/GeneratorLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/ParserLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/castas/CastAsGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/castas/CastAsParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/fieldselect/FieldSelectParser.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusCastAsTest.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusFieldSelectTest.scala
"As" feature in Focus, resolving #1028 .
Also some minor cleanup and error message improvements thrown in.  I tried to trip it up with an existential type (ie `Box[_]`), but it turned out that it was the FieldSelect feature that was really choking on this, so I've added a commented-out failing test for the FieldSelectTest.
I had to implement the `as` Prism by hand in the `CastAsGenerator` file; since it's useful enough to have privileged syntax inside Focus, it's worth thinking about whether to also add this as a standalone operator satisfying `Focus[Foo](_.bar.as[Baz]) == Focus[Foo](_.bar).as[Baz]`, then I can just reuse that one inside Focus.
If we can think of more error conditions and ways to trip it up, we can add these later.
> [Focus] `as` feature

- core/shared/src/main/scala-2.x/monocle/syntax/FocusSyntax.scala
- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/syntax/FocusSyntax.scala
- core/shared/src/main/scala/monocle/syntax/All.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusImportTest.scala
This PR adds all the `Focus` extensions `as`, `some`, etc to the import `monocle.syntax.all._`
I wonder if we should create a simpler import such as `monocle.all._` or `monocle.implicits._`
> add Focus to all syntax import

- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/FocusBase.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/GeneratorLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/ParserLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/castas/CastAsGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/each/EachGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/each/EachParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/fieldselect/FieldSelectGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/optionsome/OptionSomeGenerator.scala
- core/shared/src/main/scala-3.x/monocle/syntax/FocusSyntax.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusEachTest.scala
Adds `each` to the Focus macro, resolving #1029.
Some more bits and pieces:
- Fixed the ridiculous `composeOptics` method to be two lines, owing to a horrendous Dotty compiler space leak the old version was causing now that Traversals are in the mix.
- Removed the `ParseResult` type alias. Give it to me straight
- Removed the fully qualified `_root_.monocle.this.that....`, which is a habit I had picked up writing macros in stringier environments. They are real typechecked Scala symbols, there's no chance of ambiguity or accidental capture of some other symbol by the same name.
> [Focus] Each feature

- docs/src/main/mdoc/focus.md
- example/src/test/scala/monocle/LensExample.scala
- macro/src/main/scala-2.x/monocle/Focus.scala
- macro/src/main/scala-2.x/monocle/macros/syntax/GenApplyLensSyntax.scala
- macro/src/main/scala-2.x/monocle/macros/syntax/all.scala
- website/i18n/en.json
- website/pages/en/index.js
The idea is to make the Scala 2 and Scala 3 API as similar as possible to simplify the migration and documentation.
`Focus` will be weaker in Scala 2, only lenses for fields and it will require a different import `monocle.macro.syntax.all._`
- Add `Focus` in Scala 2 macro module which redirect to `GenLens`
- Add `focus` extension method in Scala 2 which creates an `ApplyLens`
- Start documenting `Focus` i nthe website for both Scala 3 and Scala 2. There is no version of mdoc for Scala 3 yet, so the scala 3 examples are not compiled
> Start focus documentation, add Focus to Scala 2 which redirect to GenLens

- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/FocusBase.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/FocusImpl.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/GeneratorLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/ParserBase.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/ParserLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/at/AtGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/at/AtParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/castas/CastAsParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/each/EachParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/fieldselect/FieldSelectParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/index/IndexGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/index/IndexParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/optionsome/OptionSomeParser.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusAtTest.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusEachTest.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusImportTest.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusIndexTest.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusSomeTest.scala
Adds `at` and `index` features, resolving #1030.
Of note:
- `at` feature preserves singleton index types, so as to support tuple access in the same way as `monocle.function.At`.
- Big refactor of the parser matchers for readability and type safety, based on pulling out the obvious commonality between the matchers
- All of the features with keywords (ie not field select) now use the new pretty extractors with descriptive case classes wrapping outputs, and no longer need access to the `macroContext.reflect` object.
- As usual, the tests are fairly light, and will need to be made more comprehensive later
- New module `ParserBase` that contains the `FocusParser` interface, the new `FocusKeyword` and `FocusKeywordGiven` matches and all the typesafe case class wrappers.
- `ParserBase`, …
> 'At', 'index' features + refactor of parsers for readability and type safety

- core/shared/src/main/scala-3.x/monocle/internal/focus/FocusBase.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/GeneratorLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/ParserLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/as/AsGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/as/AsParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/at/AtParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/each/EachParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/index/IndexParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/some/SomeGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/some/SomeParser.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusAsTest.scala
The inconsistent naming of Focus features was annoying me. 
The package names are now all exactly the keyword, and the `FocusAction` and matcher/parser are now called `KeywordXXX` to avoid naming collisions on things like `Some`, but still be consistent for all of them.
`FieldSelect` stays how it is. It will probably end up splitting into features called something like `SelectLens`, `SelectIso`, `SelectMulti`, `SelectGetter`, etc, so it will need its own pattern.
> More consistent naming for Focus features

- core/shared/src/test/scala-3.x/monocle/focus/FocusFieldSelectTest.scala
The problem raised in #498, that the `GenLens` macro did not allow the creation of Lenses on private case class fields, works fine with `Focus` in Monocle 3. 
I have added a test case to lock in this behaviour.
> Added test case to confirm that private case class fields can be accessed by Focus

- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/FocusBase.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/GeneratorLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/ParserBase.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/ParserLoop.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/as/AsParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/some/SomeParser.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/withdefault/WithDefaultGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/withdefault/WithDefaultParser.scala
- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/main/scala/monocle/std/Option.scala
- core/shared/src/main/scala/monocle/syntax/ApplyFold.scala
- core/shared/src/main/scala/monocle/syntax/ApplyGetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyIso.scala
- core/shared/src/main/scala/monocle/syntax/ApplyLens.scala
- core/shared/src/main/scala/monocle/syntax/ApplyOptional.scala
- core/shared/src/main/scala/monocle/syntax/ApplyPrism.scala
- core/shared/src/main/scala/monocle/syntax/ApplySetter.scala
- core/shared/src/main/scala/monocle/syntax/ApplyTraversal.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusWithDefaultTest.scala
Focus `withDefault` feature, resolving #1031 
Of note: 
- Removed the `Eq` constraint from `withDefault` in `std.option` and in all the optics, because it adds an intolerable usability hurdle to Focus, and provides little value for the `withDefault` usecase on its own
- Tweaked the `FocusKeyword` matcher in `ParserBase` to accomodate value parameters with no typeclass
> Focus withDefault feature, removed Eq constraint on withDefault everywhere

- build.sbt
- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/syntax/AppliedFocusSyntax.scala
- core/shared/src/main/scala/monocle/syntax/Apply.scala
- example/src/test/scala/monocle/LensExample.scala
- example/src/test/scala/monocle/function/AtExample.scala
- example/src/test/scala/monocle/function/EachExample.scala
- example/src/test/scala/monocle/function/FieldsExample.scala
- example/src/test/scala/monocle/function/FilterIndexExample.scala
- example/src/test/scala/monocle/function/IndexExample.scala
- macro/src/main/scala-2.x/monocle/macros/GenLens.scala
- macro/src/main/scala-2.x/monocle/macros/syntax/ApplyFocusSyntax.scala
- macro/src/main/scala-2.x/monocle/macros/syntax/all.scala
- macro/src/main/scala-2.x/monocle/macros/syntax/lens.scala
- macro/src/main/scala-3.x/monocle/macros/syntax/ApplyFocusSyntax.scala
- test/shared/src/test/scala/monocle/FoldSpec.scala
- test/shared/src/test/scala/monocle/GetterSpec.scala
- test/shared/src/test/scala/monocle/IsoSpec.scala
- test/shared/src/test/scala/monocle/LensSpec.scala
- test/shared/src/test/scala/monocle/MonocleSuite.scala
- test/shared/src/test/scala/monocle/OptionalSpec.scala
- test/shared/src/test/scala/monocle/PrismSpec.scala
- test/shared/src/test/scala/monocle/SetterSpec.scala
- test/shared/src/test/scala/monocle/TraversalSpec.scala
- test/shared/src/test/scala/monocle/function/AtSpec.scala
- test/shared/src/test/scala/monocle/syntax/FocusSyntax.scala
Fix #1064
I could make `.focus` work but not `Focus[X]`. The problem is that `Focus` uses the trick to partially apply type parameter
```scala
def apply[S] = new MkFocus[S]
class MkFocus[From] {
def apply: Iso[From, From] = Iso.id
}
```
as a result `Focus[X]` is a `MkFocus[X]` not an `Iso[X, X]`. Adding paren to `apply` fixed the ambiguity.
I had to move `.focus()` next to the macro extension `.focus(_.foo.bar)`. When both extension methods where in different classes, it confuses the compiler. 
The main issue is for Scala 2, we need define `.focus()` in the macro module.
> add Focus[X]() and .focus() for Iso/ApplyIso

- core/shared/src/main/scala-2.x/monocle/syntax/MacroSyntax.scala
- core/shared/src/main/scala-3.x/monocle/syntax/MacroSyntax.scala
- core/shared/src/main/scala/monocle/syntax/All.scala
- core/shared/src/test/scala-3.x/monocle/syntax/AsSyntaxSpec.scala
- macro/src/main/scala-2.x/monocle/macros/syntax/MacroSyntax.scala
- macro/src/main/scala-2.x/monocle/macros/syntax/all.scala
- macro/src/main/scala-3.x/monocle/macros/GenPrism.scala
- macro/src/test/scala-2.x/monocle/macros/AsSyntaxSpec.scala
For Scala 2, I added extension methods in the macro module which basically do `optic.andThen(GenPrism[To, CastTo])`.
For Scala 3, I added the same extension methods but in the core module. I could have implemented it by forwarding it to `Focus(_.as[CastTo])` but I am worried about the documentation. 
I mean for `Focus` it makes sense to use `transparent` because the return type may vary but here we know it before hand. Maybe one of you know a way to do it? Admittedly, I am just copy/pasting and tweaking code but I have no good understanding of the macro APIs.
TODO in another PR, do the same for `ApplyOptics`.
> add as extension method to optics in Scala 2 and 3

- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/KeywordParserBase.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/as/AsGenerator.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/features/as/AsParser.scala
- core/shared/src/main/scala-3.x/monocle/syntax/MacroSyntax.scala
- core/shared/src/test/scala-3.x/monocle/focus/FocusAsTest.scala
- Thanks to Scala 3 RC1, adds a `From` parameter to the Focus `as` keyword, constrained by a type bounds. This is now the same signature as the external `as` operator:
```
extension [From] (from: From)
def as[CastTo <: From]: CastTo
```
-  Adds a case to the `FocusKeyword` pattern matcher to correctly interpret an extension method with both inferred and direct type parameter lists.
- Renamed `GenPrism` to `AsPrism`. It is no longer analogous to the deprecated `GenXXX` features, and should not forward to `Focus`. It is an implementation detail for the new and supported `as` operator.
- Changed the `AsGenerator` implementation to directly use `AsPrism`, rather than have its own operation. This is now the same as the other features, which all generate code that delegates to the external …
> Brings `as` into line with the other operators wrt Focus

- build.sbt
- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- example/src/test/scala/monocle/generic/CoproductExample.scala
I doubt these methods see much use. We implemented them because we could but it is pain to mainten and it pollutes the interface.
> Deprecate first, second, left, right, split. Move choice to cats instance

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
We don't need the other ones now that we have inheritance between optics.
> Deprecate all except Lens codiagonal

- core/shared/src/main/scala-3.x/monocle/Focus.scala
- core/shared/src/main/scala-3.x/monocle/internal/focus/ComposedFocusImpl.scala
- core/shared/src/main/scala-3.x/monocle/syntax/All.scala
- core/shared/src/main/scala-3.x/monocle/syntax/ComposedFocusSyntax.scala
- core/shared/src/test/scala-3.x/monocle/focus/ComposedFocusTest.scala
- Adds extension method `refocus` to all optics & applied optics, which is equivalent to `optic.andThen(Focus[Foo](_.....))`.
- Resolves #1056
- Must be an extension method rather than a direct method on optics, so as to cleanly separate the macro code.
- Astonishingly, can treat all optics and applied optics uniformly with only one simple implementation.
- Privately defines a `type AnyOptic[S,A] = Setter[S,A] | Fold[S,A] | AppliedSetter[S,A] | AppliedFold[S,A]`. Should this be a public definition? Probably not, because its usage is not likely to be meaningful beyond this macro, and would be highly susceptible to change.
- Big fat test suite testing many combinations of optic types, and especially `Getter` and `Fold`, since they are special cases, because their `andThen` method only has …
> Refocus feature

- build.sbt
I am only getting one error when I run mima locally. It seems to be related to platform specific string.
```scala
[error] macros: Failed binary compatibility check against dev.optics:monocle-macro_2.13:3.0.0! Found 2 potential problems
[error]  * static method stringToURL()monocle.PPrism in class monocle.Monocle does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("monocle.Monocle.stringToURL")
[error]  * method stringToURL()monocle.PPrism in object monocle.Monocle does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("monocle.Monocle.stringToURL")
[error] core: Failed binary compatibility check against dev.optics:monocle-core_2.13:3.0.0! Found 4 …
```
> update mima settings

- core/shared/src/main/scala/monocle/Fold.scala
- core/shared/src/main/scala/monocle/Getter.scala
- core/shared/src/main/scala/monocle/Iso.scala
- core/shared/src/main/scala/monocle/Lens.scala
- core/shared/src/main/scala/monocle/Optional.scala
- core/shared/src/main/scala/monocle/Prism.scala
- core/shared/src/main/scala/monocle/Setter.scala
- core/shared/src/main/scala/monocle/Traversal.scala
- core/shared/src/test/scala/monocle/CatsCompatTest.scala
Fix for #1183 
- Index is now a direct method on all optics, instead of an extension method
- new private method on all polymorphic optics `adaptMono`
> index is now a direct method, for better Cats compat

- macro/src/main/scala-2.x/monocle/macros/internal/Macro.scala
- macro/src/test/scala-2.x/monocle/macros/internal/ContextBoundCompilationIssueSpec.scala
Will (mostly) solve #1259 for Scala 2.13.
> Fix GenLens issue with evidence shadowing

- build.sbt
This was my mistake in https://github.com/optics-dev/Monocle/pull/1307, causing the version in the API docs to render as `vSome(3.1.0)` and breaking the sourcecode links. Sorry!
> Fix version in API docs

- .github/workflows/ci.yml
- build.sbt
This broke after the upgrade in https://github.com/optics-dev/Monocle/pull/1384.
> Fix mdoc step in CI

- build.sbt
- core/shared/src/main/scala-3/monocle/internal/focus/ErrorHandling.scala
- core/shared/src/main/scala-3/monocle/internal/focus/FocusBase.scala
- core/shared/src/main/scala-3/monocle/internal/focus/FocusImpl.scala
- core/shared/src/main/scala-3/monocle/internal/focus/features/SelectParserBase.scala
- core/shared/src/main/scala-3/monocle/internal/focus/features/selectfield/SelectFieldParser.scala
- core/shared/src/main/scala-3/monocle/internal/focus/features/selectonlyfield/SelectOnlyFieldParser.scala
A few random changes which are (mostly) forced by compiler changes.
1. The inferred type for inline lambas is different, so we get this awfully confusing error message currently:
```
Cannot generate Lens for field 'foo', because '_$1' is not a case class
```
2. We can now report a position error within a macro so the language servers should be able to point to the right part of the code.
I think I'll change the hierarchy of the `FocusError` a little, because some of the errors are internal i.e. `5xx` and some are `4xx`; mixing them is quite confusing.
> Improve error messages for the `Focus` macro.
